name: CI

on:
  push:
    # We want to auto-accept these baselines
    branches:
      - master
      - '[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.[0-9]+.x'

jobs:
  visual-regression-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        exitOnceUploaded: true
        autoAcceptChanges: true