name: CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ">=18.12.1 18"
      - run: npm ci
      - run: npx prettier --check './src/**/*.{js,jsx,ts,tsx}'
      - run: npm run lint
      - run: npm run type-check
  test:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
