name: CI

on:
  push:
    # There is no need to run CI again because we use  "Require branches to be up to date before merging"
    branches-ignore:    
      - master
      - '[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.[0-9]+.x'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - run: npm run lint
    - run: npm run lint-ts
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - run: npm test