name: Semantic Release

on:
  push:
    # These are the branches that we expect to publish from
    # semantic-release also has a regex that validates we're running on a release branch
    branches:    
      - master
      - '[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.[0-9]+.x'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - run: npx semantic-release
      env:
        # A personal access token is required to publish from protected branches
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}